from selenium import webdriver
driver =webdriver.Chrome(executable_path=r"C:\Users\HP\PycharmProjects\seleniumex3\driver\chromedriver.exe")
import time
driver.get("http://demo.actitime.com/")
time.sleep(4)
driver.find_element_by_id("username").send_keys("admin")
time.sleep(2)
driver.find_element_by_class_name("ico-register").click()
time.sleep(2)
driver.find_element_by_id("gender-female").click()
time.sleep(2)
driver.find_element_by_name("FirstName").send_keys("madhuri")
time.sleep(2)
driver.find_element_by_id("LastName").send_keys("chandra")
time.sleep(2)
driver.find_element_by_id("Email").send_keys("madhurichandra.v.e@gmail.com")
time.sleep(2)
driver.find_element_by_id("Password").send_keys("890890890")
time.sleep(2)
driver.find_element_by_id("ConfirmPassword").send_keys("890890890")
time.sleep(2)
driver.find_element_by_name("register-button").click()